"""Search over whole TURNS, with the real policy as the continuation.

Every override tried in this project second-guessed ONE decision inside a
multi-action turn, and every one lost:

    greedy rollout leaf            0.3025
    value-net rollout leaf         0.4216   (void: broken evaluator, see below)
    value-net 1-ply, no rollout    0.4520   (void, same reason)
    baseline                       0.521

A turn here is a plan -- fetch, bench, attach, evolve, attack -- and the
rule-based policy plans it coherently. Swapping out one step wrecks the plan the
step belonged to, which fits all three failures including the 1-ply one that had
no rollout noise and no opponent guess at all.

So this searches at the level the game is actually played: for each candidate
FIRST action, play the rest of the turn **with the real policy**, then score the
end-of-turn position. Two things make that possible and both were verified:

  * `dataclasses.asdict` round-trips a simulated Observation exactly -- the
    policy returns identical actions on the original dict and the reconstructed
    one -- so the real policy can be driven on simulated states.
  * a full turn simulates in ~24.5 ms, against a 600 s episode budget.

The leaf is `valnet.score_raw`, NOT `score`. An earlier build shipped weights
trained on a different featuriser than it vendored; the raw output sat far
outside [0,1], the old clamp returned a constant for 94% of positions, and two
"value nets do not work" results were measuring noise.

Averages over DETS determinizations so a single lucky shuffle cannot decide the
turn, and overrides only when the best plan beats the policy's own plan by
MARGIN -- validate, do not replace.

  python work/tools/build_turn_planner.py --name w100_turnplan
"""
import argparse
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.dirname(HERE)
AGENTS = os.path.join(WORK, "agents")
LIB = os.path.join(WORK, "lib")

MAIN = r'''"""v28's policy, with a whole-TURN lookahead. Generated by build_turn_planner.py."""
import dataclasses
import random
import time

import policy_features as pf
from policies.v28 import main as _pol

DECK = list(pf.DECK)

BUDGET_S = __BUDGET__
DETS = __DETS__
CANDS = __CANDS__
MARGIN = __MARGIN__
MAX_TURN_STEPS = 40

try:
    from cg.api import (SelectContext, search_begin, search_release,
                        search_step, to_observation_class)
    import valfeat as _valfeat
    import valnet as _valnet
    _OK = True
except Exception:
    _OK = False

_STATS = {"planned": 0, "overrode": 0, "errors": 0}


def _legal_dict(action, sel):
    if not isinstance(action, (list, tuple)):
        return False
    n = len(sel.get("option") or [])
    lo = int(sel.get("minCount", 0) or 0)
    hi = int(sel.get("maxCount", 0) or 0)
    return (lo <= len(action) <= hi and len(action) == len(set(action))
            and all(isinstance(i, int) and 0 <= i < n for i in action))


def _legal_cls(action, sel):
    n = len(sel.option or [])
    lo = int(sel.minCount or 0)
    hi = int(sel.maxCount or 0)
    return (isinstance(action, list) and lo <= len(action) <= hi
            and len(action) == len(set(action))
            and all(isinstance(i, int) and 0 <= i < n for i in action))


def _determinize(o, me_idx):
    """Deal our unseen cards and a mirror-prior opponent. Counts must match."""
    me = o.current.players[me_idx]
    opp = o.current.players[1 - me_idx]
    mine = list(DECK)
    random.shuffle(mine)
    nd, npz = int(me.deckCount or 0), len(me.prize or [])
    yd, yp = mine[:nd], mine[nd:nd + npz]
    while len(yp) < npz:
        yp.append(mine[0])
    ref = list(DECK)
    random.shuffle(ref)
    od, op_, oh = (int(opp.deckCount or 0), len(opp.prize or []),
                   int(opp.handCount or 0))
    while len(ref) < od + op_ + oh:
        ref = ref + list(DECK)
    return yd, yp, ref[:od], ref[od:od + op_], ref[od + op_:od + op_ + oh]


def _play_out_turn(o, me_idx, det, first):
    """Apply `first`, finish the turn WITH THE POLICY, score the end state."""
    sid = None
    try:
        yd, yp, od, op_, oh = det
        st = search_begin(o, list(yd), list(yp), list(od), list(op_),
                          list(oh), [DECK[0]], True)
        sid = st.searchId
        turn0 = o.current.turn
        nxt = search_step(sid, list(first))
        so = None
        steps = 0
        while nxt is not None and nxt.observation is not None:
            so, sid = nxt.observation, nxt.searchId
            steps += 1
            cur = so.current
            if cur is None or cur.result != -1:
                break
            if cur.turn != turn0 or steps >= MAX_TURN_STEPS:
                break
            if so.select is None or not (so.select.option or []):
                break
            try:
                act = _pol.agent(dataclasses.asdict(so))
            except Exception:
                act = None
            if not _legal_cls(act, so.select):
                lo = max(1, int(so.select.minCount or 1))
                act = list(range(min(lo, len(so.select.option or []))))
            nxt = search_step(sid, list(act))
        if so is None:
            return None
        cur = so.current
        if cur is not None and cur.result != -1:
            return 1e6 if cur.result == me_idx else -1e6
        f = _valfeat.features(so, me_idx)
        if f is None:
            return None
        return 1000.0 * float(_valnet.score_raw(f))
    except Exception:
        _STATS["errors"] += 1
        return None
    finally:
        if sid is not None:
            try:
                search_release(sid)
            except Exception:
                pass


def _plan(obs, baseline):
    o = to_observation_class(obs)
    if o.current is None or getattr(o, "search_begin_input", None) is None:
        return None
    sel = obs.get("select") or {}
    opts = sel.get("option") or []
    if len(opts) < 2 or int(sel.get("maxCount", 1) or 1) != 1:
        return None
    me_idx = int(o.current.yourIndex)

    cands = [[i] for i in range(min(len(opts), CANDS))]
    if list(baseline) not in cands and _legal_dict(baseline, sel):
        cands.append(list(baseline))
    deadline = time.time() + BUDGET_S
    dets = [_determinize(o, me_idx) for _ in range(DETS)]

    best, best_v = None, None
    base_v = None
    for c in cands:
        vals = []
        for det in dets:
            if time.time() > deadline:
                break
            v = _play_out_turn(o, me_idx, det, c)
            if v is not None:
                vals.append(v)
        if not vals:
            continue
        avg = sum(vals) / len(vals)
        if list(c) == list(baseline):
            base_v = avg
        if best_v is None or avg > best_v:
            best, best_v = list(c), avg
    _STATS["planned"] += 1
    if best is None or base_v is None or best == list(baseline):
        return None
    if best_v - base_v <= MARGIN:
        return None
    _STATS["overrode"] += 1
    return best


def agent(obs):
    if not obs or obs.get("select") is None:
        try:
            _pol.agent(obs)
        except Exception:
            pass
        return list(DECK)
    try:
        base = list(_pol.agent(obs))
    except Exception:
        base = None
    sel = obs.get("select") or {}
    if base is None or not _legal_dict(base, sel):
        n = len(sel.get("option") or [])
        base = list(range(min(n, max(1, int(sel.get("minCount", 1) or 1)))))
    if not _OK:
        return base
    try:
        ctx = int(sel.get("context", -1) if sel.get("context") is not None
                  else -1)
        if ctx == int(SelectContext.MAIN):
            alt = _plan(obs, base)
            if alt is not None and _legal_dict(alt, sel):
                return alt
    except Exception:
        pass
    return base
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="_sub_v28")
    ap.add_argument("--name", default="w100_turnplan")
    ap.add_argument("--budget", type=float, default=4.0)
    ap.add_argument("--dets", type=int, default=4)
    ap.add_argument("--cands", type=int, default=5)
    ap.add_argument("--margin", type=float, default=40.0)
    a = ap.parse_args()

    src = (MAIN.replace("__BUDGET__", repr(a.budget))
              .replace("__DETS__", repr(a.dets))
              .replace("__CANDS__", repr(a.cands))
              .replace("__MARGIN__", repr(a.margin)))
    compile(src, "main.py", "exec")

    dst = os.path.join(AGENTS, a.name)
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    shutil.copytree(os.path.join(AGENTS, a.base), dst,
                    ignore=shutil.ignore_patterns("__pycache__"))
    with open(os.path.join(dst, "main.py"), "w", encoding="utf-8") as f:
        f.write(src)
    for need in ("valfeat.py", "valnet.py"):
        p = os.path.join(LIB, need)
        if not os.path.exists(p):
            raise SystemExit(f"work/lib/{need} missing -- train the net first")
        shutil.copy2(p, os.path.join(dst, need))

    print(f"built work/agents/{a.name} from {a.base}")
    print(f"   budget {a.budget}s  dets {a.dets}  cands {a.cands}  "
          f"margin {a.margin}")
    print("   continuation = THE REAL POLICY (v28), leaf = valnet.score_raw")
    return 0


if __name__ == "__main__":
    sys.exit(main())
