"""A deck-agnostic pilot, so we can measure archetypes nobody has published.

The field panel covers 62% of the top 50. Mega Lopunny is 18% of it and has
never been measured once, because no Lopunny agent exists anywhere -- and the
"unknown" archetypes are another 16%. That is more than a third of the field we
have been blind to while tuning against the part we can see.

This builds an opponent for any real decklist. The pilot is deliberately simple
and deck-agnostic, which is honest about what it is: development first, then the
attack that does the most damage (doubling for Weakness, preferring one that
knocks out), then end the turn -- because attacking ends it. That is the same
rule set that made the search's rollouts work, and it is roughly the standard of
the published rule-based agents already on the panel.

It is NOT a top-50 Lopunny pilot and must not be read as one. A cell measured
against it says "how do we do against this DECK played competently", which is
the question we currently cannot answer at all.

  python work/tools/build_generic_pilot.py --deck work/out/lopunny_deck.csv \
      --name x_lopunny
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.dirname(HERE)
AGENTS = os.path.join(WORK, "agents")

MAIN = r'''"""Deck-agnostic knockout-aware pilot. Generated by build_generic_pilot.py."""
from cg.api import OptionType, SelectContext, all_attack, all_card_data, \
    to_observation_class

_ATK = {a.attackId: a for a in all_attack()}
_CARD = {c.cardId: c for c in all_card_data()}
DECK = __DECK__

# Development before attacking, because attacking ends the turn. Abilities first
# since they are usually free, then evolution, then cards, then energy.
_PREF = {
    int(OptionType.ABILITY): 6,
    int(OptionType.EVOLVE): 5,
    int(OptionType.PLAY): 4,
    int(OptionType.ATTACH): 3,
    int(OptionType.ATTACK): 2,
    int(OptionType.RETREAT): 1,
    int(OptionType.END): 0,
}
_ABILITY_CAP = 6            # an unbounded Ability loop is a known engine hang


def _damage(o, opt):
    a = _ATK.get(int(getattr(opt, "attackId", 0) or 0))
    if a is None or not a.damage:
        return 0.0, False
    dmg = float(a.damage)
    try:
        st = o.current
        me = st.players[st.yourIndex]
        opp = st.players[1 - st.yourIndex]
        mine = me.active[0] if (me.active and me.active[0]) else None
        tgt = opp.active[0] if (opp.active and opp.active[0]) else None
        if mine is not None and tgt is not None:
            tc, mc = _CARD.get(tgt.id), _CARD.get(mine.id)
            if (tc is not None and mc is not None
                    and getattr(tc, "weakness", None) is not None
                    and int(tc.weakness) == int(mc.energyType)):
                dmg *= 2.0
            return dmg, dmg >= float(tgt.hp)
    except Exception:
        pass
    return dmg, False


_STATE = {"abilities": 0, "turn": -1}


def agent(obs_dict):
    if (isinstance(obs_dict, dict) and obs_dict.get("current") is None
            and obs_dict.get("select") is None):
        _STATE["abilities"] = 0
        _STATE["turn"] = -1
        return list(DECK)
    try:
        o = to_observation_class(obs_dict)
        sel = o.select
        if sel is None:
            return list(DECK)
        opts = sel.option or []
        n = len(opts)
        if n == 0:
            return []
        lo = max(1, int(sel.minCount or 1))
        hi = int(sel.maxCount or lo)
        k = min(max(lo, 1), n)

        if sel.context != SelectContext.MAIN:
            return list(range(min(k, n)))

        turn = int(o.current.turn or 0)
        if turn != _STATE["turn"]:
            _STATE["turn"] = turn
            _STATE["abilities"] = 0

        best_i, best_s = 0, -1e18
        for i, opt in enumerate(opts):
            t = int(opt.type)
            s = float(_PREF.get(t, 1))
            if t == int(OptionType.ATTACK):
                dmg, ko = _damage(o, opt)
                s = 20.0 + dmg / 1000.0 if ko else 2.0 + dmg / 100000.0
            elif t == int(OptionType.ABILITY):
                if _STATE["abilities"] >= _ABILITY_CAP:
                    s = -1.0
            if s > best_s:
                best_i, best_s = i, s
        if int(opts[best_i].type) == int(OptionType.ABILITY):
            _STATE["abilities"] += 1
        out = [best_i]
        if not (lo <= len(out) <= max(hi, lo)):
            out = list(range(min(max(lo, 1), n)))
        return out
    except Exception:
        try:
            s = to_observation_class(obs_dict).select
            return list(range(min(max(1, int(s.minCount or 1)),
                                  len(s.option or []))))
        except Exception:
            return [0]
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deck", required=True)
    ap.add_argument("--name", required=True)
    a = ap.parse_args()

    sys.path.insert(0, os.path.join(WORK, "lib"))
    from cg.game import battle_finish, battle_start

    deck = sorted(int(x) for x in open(a.deck, encoding="utf-8-sig").read()
                  .split() if x.strip())
    if len(deck) != 60:
        raise SystemExit(f"deck has {len(deck)} cards, not 60")
    obs, _ = battle_start(list(deck), list(deck))
    ok = obs is not None
    battle_finish()
    if not ok:
        raise SystemExit("engine REJECTED the deck")

    out = os.path.join(AGENTS, a.name)
    os.makedirs(out, exist_ok=True)
    src = MAIN.replace("__DECK__", repr(deck))
    compile(src, "main.py", "exec")
    with open(os.path.join(out, "main.py"), "w", encoding="utf-8") as f:
        f.write(src)
    with open(os.path.join(out, "deck.csv"), "w", encoding="utf-8") as f:
        f.write("\n".join(map(str, deck)) + "\n")
    print(f"built work/agents/{a.name}  (engine accepts the 60)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
