"""Route each matchup to whichever of our two pilots actually wins it.

w34_koroll and _sub_v28 are THE SAME BUNDLE. Byte-compared: 187 identical files,
differing only in main.py (w34 additionally ships opp_library.py and
search_validator.py). w34's main.py runs the full ensemble; _sub_v28's calls
policies/v28/main.py directly and bypasses it. So both pilots already live
inside the agent we ship, and choosing between them needs no vendoring, no
renamed packages, and no second copy of anything.

They are not the same strength, and neither dominates:

    matchup      w34      v28      delta   sigma   true weight
    Grimmsnarl   0.5676   0.5253   -0.042   0.8     0.32
    Alakazam     0.7258   0.7581   +0.032   0.6     0.14
    Crustle      0.8441   0.7838   -0.060   1.2     0.10
    Dragapult    0.6613   0.8280   +0.167   3.2     0.04
    Lucario      0.5484   0.6720   +0.124   2.4     0.06

Only two of those clear noise, and both favour v28, so only those two are
routed. Handing v28 the mirror on a 0.8-sigma reading would be picking the
larger of two coin flips -- the exact winner's-curse this repo keeps paying for.
Mega Lucario is weighted 0.06 here, not the panel's 0.02: the top-50 re-survey
found 3 of 50 teams on it, and it is our worst matchup.

BOTH pilots are driven on every observation and only the selected answer is
used. They keep internal state (turn counters, guards, history), so a pilot that
were only consulted from the turn we identify the opponent would be reasoning
from a board it had never seen. The cost is one extra policy call per decision,
against a 600 s episode allowance the base uses 12 s of.

Verify before believing: the router MUST reproduce w34's mirror number and v28's
Dragapult number. If it does not, the two pilots are interfering through shared
module state and every routed cell is meaningless.

  python work/tools/build_router.py --name w70_route
"""
import argparse
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.dirname(HERE)
AGENTS = os.path.join(WORK, "agents")

# Card ids unique to one panel deck, from work/tools/archetype_ids.py. Only
# cards that appear in EXACTLY ONE archetype are usable as a tell.
MAIN = r'''"""Matchup router over two pilots that already share this bundle.

Generated by work/tools/build_router.py -- see that file for the measurements.
"""
import ensemble_pilot as _w34
from policies.v28 import main as _v28
import policy_features as pf

DECK = list(pf.DECK)

# Opponent card id -> archetype. Unique tells only; a card two decks share
# says nothing.
_TELL = {}
for _cid in (119, 120, 121, 184, 235, 1071):
    _TELL[_cid] = "dragapult"
for _cid in (673, 674, 675, 676, 677, 678):
    _TELL[_cid] = "lucario"

# Archetype -> pilot. Anything not named here keeps the ensemble, which is the
# incumbent and holds the mirror.
_TO_V28 = {"dragapult", "lucario"}

_S = {"profile": None, "locked": False}


def _reset():
    _S["profile"] = None
    _S["locked"] = False


def _sniff(obs):
    """Name the opponent from what they have revealed. Sticky once found."""
    if _S["locked"]:
        return _S["profile"]
    try:
        cur = obs.get("current") or {}
        players = cur.get("players") or []
        if len(players) < 2:
            return None
        them = players[1 - int(cur.get("yourIndex", 0) or 0)]
        for zone in ("active", "bench", "discard"):
            for card in (them.get(zone) or []):
                if not isinstance(card, dict):
                    continue
                cid = int(card.get("id", card.get("cardId", 0)) or 0)
                name = _TELL.get(cid)
                if name:
                    _S["profile"] = name
                    _S["locked"] = True
                    return name
    except Exception:
        pass
    return None


def _legal(action, sel):
    if not isinstance(action, (list, tuple)):
        return False
    n = len(sel.get("option") or [])
    lo = int(sel.get("minCount", 0) or 0)
    hi = int(sel.get("maxCount", 0) or 0)
    return (lo <= len(action) <= hi and len(action) == len(set(action))
            and all(isinstance(i, int) and 0 <= i < n for i in action))


def agent(obs):
    if not obs or obs.get("select") is None:
        _reset()
        for fn in (_w34.agent, _v28.agent):
            try:
                fn(obs)
            except Exception:
                pass
        return list(DECK)

    # Drive BOTH pilots so neither is ever reasoning from a board it has not
    # seen, then use only the one this matchup belongs to.
    try:
        a_ens = list(_w34.agent(obs))
    except Exception:
        a_ens = None
    try:
        a_v28 = list(_v28.agent(obs))
    except Exception:
        a_v28 = None

    sel = obs.get("select") or {}
    profile = _sniff(obs)
    first = a_v28 if profile in _TO_V28 else a_ens
    second = a_ens if profile in _TO_V28 else a_v28
    for cand in (first, second):
        if cand is not None and _legal(cand, sel):
            return cand
    n = len(sel.get("option") or [])
    return list(range(min(n, int(sel.get("maxCount", 0) or 0))))
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="w34_koroll")
    ap.add_argument("--name", default="w70_route")
    a = ap.parse_args()

    src_dir = os.path.join(AGENTS, a.base)
    dst = os.path.join(AGENTS, a.name)
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    shutil.copytree(src_dir, dst, ignore=shutil.ignore_patterns("__pycache__"))

    # The ensemble currently lives in main.py; move it aside so the router can
    # import it as a module instead of re-implementing it.
    shutil.move(os.path.join(dst, "main.py"),
                os.path.join(dst, "ensemble_pilot.py"))
    compile(MAIN, "main.py", "exec")
    with open(os.path.join(dst, "main.py"), "w", encoding="utf-8") as f:
        f.write(MAIN)

    print(f"built work/agents/{a.name} from {a.base}")
    print("  ensemble -> ensemble_pilot.py, router -> main.py")
    print("  routed to v28: dragapult, lucario;  everything else: ensemble")
    print("\nVERIFY BEFORE BELIEVING -- the router must reproduce both parents:")
    print(f"  gauntlet {a.name} vs s_dragapult   should match v28's 0.828")
    print(f"  gauntlet {a.name} vs w5_grimmsnarl should match w34's 0.568")
    return 0


if __name__ == "__main__":
    sys.exit(main())
