"""Turn scraped leaderboard decks into work/lib/meta_decks.py for bundling.

Deduplicates identical lists and keeps the highest-scoring example of each, so
the opponent matcher searches a small library of distinct archetypes rather
than 100 near-copies.
"""
import json
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.dirname(HERE)
SRC = os.path.join(WORK, "out", "meta_decks.json")
DST = os.path.join(WORK, "lib", "meta_decks.py")

if not os.path.exists(SRC):
    raise SystemExit(f"no scraped decks at {SRC}; run scrape_decks.py first")

with open(SRC, encoding="utf-8") as f:
    store = json.load(f)

teams = store.get("teams", {})
uniq = {}
for t in teams.values():
    deck = t.get("deck")
    if not deck or len(deck) != 60:
        continue
    key = tuple(sorted(deck))
    prev = uniq.get(key)
    if prev is None or t.get("score", 0) > prev["score"]:
        uniq[key] = {"deck": sorted(deck), "score": t.get("score", 0),
                     "rank": t.get("rank"), "n": 1}
    else:
        prev["n"] += 1

rows = sorted(uniq.values(), key=lambda r: -r["score"])

sys.path.insert(0, os.path.join(WORK, "lib"))
from cg.api import all_card_data  # noqa: E402
cards = {c.cardId: c for c in all_card_data()}


def label(deck):
    cnt = Counter(deck)
    ex = [f"{cards[c].name} x{n}" for c, n in cnt.items()
          if c in cards and int(cards[c].cardType) == 0
          and (cards[c].megaEx or cards[c].ex)]
    return " + ".join(sorted(ex)) or "(no ex line)"


lines = [
    '"""Opponent decklists scraped from public leaderboard replays.',
    "",
    "AUTOGENERATED by work/tools/build_meta_module.py -- do not hand-edit.",
    "Used by fsearch.match_opponent_deck to determinize the opponent's hidden",
    "zones with a real list instead of filler cards.",
    '"""',
    "",
    "DECKS = [",
]
for r in rows:
    lines.append(f"    # score {r['score']:.1f} (rank {r['rank']}), "
                 f"{r['n']} team(s): {label(r['deck'])}")
    d = r["deck"]
    for i in range(0, 60, 10):
        lines.append("    " + ("[" if i == 0 else " ")
                     + ", ".join(str(x) for x in d[i:i + 10])
                     + ("," if i + 10 < 60 else "],"))
lines.append("]")
lines.append("")

os.makedirs(os.path.dirname(DST), exist_ok=True)
with open(DST, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"{len(teams)} teams scraped -> {len(rows)} distinct decklists")
print(f"wrote {DST}")
for r in rows[:15]:
    print(f"  {r['score']:>7.1f}  x{r['n']:<2} {label(r['deck'])}")
