"""Rebuild the opponent-deck library from the decks we ACTUALLY face.

Why this exists. `fsearch.Determinizer` fills the opponent's hidden zones by
matching what we have seen them play against a library of real decklists. When
nothing matches it pads with filler -- one Basic Pokemon and a pile of Energy.
Every playout or lookahead from that point is a game against a deck that does
not exist, which is a complete explanation for why every search variant tried
here lost:

    1-ply + hand-written evaluate()   v30  0.3500
    2-ply + PIMC, same evaluator      v31  0.0530
    1-ply + learned value net leaf    v33  0.3667
    full playouts to terminal         v53  0.4182

The library was scraped from LEADERBOARD replays, so it is all ex / Mega-ex
archetypes. Measured against it:

    Archaludon ex   present in  0 / 31 decks   (9.4% of our games, we win 0.29)
    Cinderace       present in  0 / 31         (we win 0.167)
    Alakazam        present in  2 / 31         (18.8% of our games)

i.e. the decks we lose to most are exactly the ones it cannot represent.

This rebuilds the library from two sources that DO contain them:
  * the opponent decklists in our own downloaded ladder replays -- by
    construction, the decks our matchmaking band actually plays
  * the scraped leaderboard decks, for the strong lists we have not met yet

Usage:
  python work/tools/build_meta_from_replays.py
"""
import json
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
WORK = os.path.dirname(HERE)
OUT = os.path.join(WORK, "out")
STORE = os.path.join(OUT, "our_replays")
DST = os.path.join(WORK, "lib", "meta_decks.py")

sys.path.insert(0, os.path.join(WORK, "lib"))
from cg.api import all_card_data  # noqa: E402

CARDS = {c.cardId: c for c in all_card_data()}
NAMERS = [
    (743, "Alakazam"), (190, "Archaludon ex"), (666, "Cinderace"),
    (648, "Marnie's Grimmsnarl ex"), (678, "Mega Lucario ex"),
    (849, "Mega Lopunny ex"), (345, "Crustle"), (121, "Dragapult ex"),
    (723, "Mega Abomasnow ex"), (96, "Teal Mask Ogerpon ex"),
    (756, "Mega Kangaskhan ex"), (1071, "Meowth ex"), (143, "Snorlax"),
    (140, "Fezandipiti ex"), (306, "Dudunsparce ex"), (431, "TR Mewtwo ex"),
    (381, "Cynthia's Garchomp ex"), (1032, "Mega Starmie ex"),
]


def label(deck):
    s = set(deck)
    for cid, name in NAMERS:
        if cid in s:
            return name
    return "unknown"


def from_replays():
    """Opponent decklists from our own ladder replays."""
    out = []
    meta_path = os.path.join(OUT, "our_episodes.json")
    if not os.path.exists(meta_path):
        return out
    meta = json.load(open(meta_path, encoding="utf-8"))
    for w in meta:
        p = os.path.join(STORE, f"{w['episode']}.json")
        if not os.path.exists(p):
            continue
        try:
            d = json.load(open(p, encoding="utf-8"))
        except Exception:
            continue
        oi = 1 - w["my_index"]
        for st in (d.get("steps") or [])[:3]:
            if oi < len(st) and isinstance(st[oi].get("action"), list) \
                    and len(st[oi]["action"]) == 60:
                out.append(([int(x) for x in st[oi]["action"]], "replay"))
                break
    return out


def from_scrape():
    p = os.path.join(OUT, "meta_decks.json")
    if not os.path.exists(p):
        return []
    store = json.load(open(p, encoding="utf-8"))
    out = []
    for t in store.get("teams", {}).values():
        d = t.get("deck")
        if d and len(d) == 60:
            out.append(([int(x) for x in d], "scrape"))
    return out


def from_bundled_opponents():
    """The published opponent agents we benchmark against play real lists too."""
    out = []
    for name in ("w1_alakazam", "w2_archaludon", "s_dragapult", "s_mega",
                 "w3_alakazam_guard", "w4_alakazam_search"):
        p = os.path.join(WORK, "agents", name, "deck.csv")
        if os.path.exists(p):
            d = [int(x) for x in open(p, encoding="utf-8").read().split() if x.strip()]
            if len(d) == 60:
                out.append((d, "agent:" + name))
    return out


def main():
    all_decks = from_replays() + from_scrape() + from_bundled_opponents()
    uniq = {}
    src_count = Counter()
    for deck, src in all_decks:
        key = tuple(sorted(deck))
        if key not in uniq:
            uniq[key] = src
            src_count[src.split(":")[0]] += 1
    by_arch = Counter(label(list(k)) for k in uniq)

    print(f"{len(all_decks)} decklists seen, {len(uniq)} distinct")
    print("sources:", dict(src_count))
    print("\ncoverage by archetype:")
    for k, v in by_arch.most_common():
        print(f"  {k:<26} {v}")

    lines = ['"""Opponent decklists for determinizing the opponent\'s hidden zones.',
             "",
             "AUTOGENERATED by work/tools/build_meta_from_replays.py -- do not hand-edit.",
             "",
             "Built from the decks we ACTUALLY face (opponent lists pulled out of our own",
             "downloaded ladder replays) plus scraped leaderboard lists and the published",
             "opponent agents we benchmark against. The previous library was scraped from",
             "leaderboard replays only, so it was all ex/Mega-ex archetypes and contained",
             "ZERO Archaludon and ZERO Cinderace decks -- two of the three matchups we lose",
             "most. fsearch falls back to filler when nothing matches, so every lookahead",
             "in those games was a simulation against a deck that does not exist.",
             '"""',
             "",
             "DECKS = ["]
    for key, src in sorted(uniq.items(), key=lambda kv: label(list(kv[0]))):
        deck = list(key)
        lines.append(f"    # {label(deck)}  [{src}]")
        for i in range(0, 60, 10):
            lines.append("    " + ("[" if i == 0 else " ")
                         + ", ".join(str(x) for x in deck[i:i + 10])
                         + ("," if i < 50 else "],"))
    lines.append("]")
    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nwrote {DST} with {len(uniq)} decklists")


if __name__ == "__main__":
    main()
